name       : mate-media
version    : 1.24.1
release    : 22
source     :
    - https://github.com/mate-desktop/mate-media/releases/download/v1.24.1/mate-media-1.24.1.tar.xz : 222d75d6105a2665f7f0f5e44480917223eca6fc120eebd673703c1105271185
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    This package contains a few media utilities for the MATE desktop, including a volume control.
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(mate-desktop-2.0)
rundeps    :
    - sound-theme-freedesktop
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
