name       : mate-media
version    : 1.22.1
release    : 15
source     :
    - https://github.com/mate-desktop//mate-media/archive/v1.22.1.tar.gz : eec68a14a35617d6a18ec18765adaa9094ea66bc2bad4dbc82cedf148e83e327
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    This package contains a few media utilities for the MATE desktop, including a volume control.
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(mate-desktop-2.0)
    - mate-common
rundeps    :
    - sound-theme-freedesktop
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
