name       : mate-media
version    : 1.20.2
release    : 13
source     :
    - https://github.com/mate-desktop/mate-media/archive/v1.20.2.tar.gz : fa9ef66eb69978dff8dbe0a78826923bd3dbe80551e6bc2704a980b47d7e4650
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    MATE Volume Control Applet
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(mate-desktop-2.0)
    - mate-common
rundeps    :
    - sound-theme-freedesktop
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
