name       : mate-media
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-media-1.16.0.tar.xz : 87a6aab1635cdf0890b4f99b733eb786144c90730a96d04c41e05ea781cd0a20
license    :
    - GPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    MATE Volume Control Applet
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(unique-3.0)
rundeps    :
    - sound-theme-freedesktop
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
