name       : mate-media
version    : 1.27.0
release    : 25
source     :
    - https://github.com/mate-desktop/mate-media/releases/download/v1.27.0/mate-media-1.27.0.tar.xz : b64e3ea0525001ea48cc8fdcc2436591bbf994d385968883227cff93af6c8842
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    This package contains a few media utilities for the MATE desktop, including a volume control.
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(mate-desktop-2.0)
rundeps    :
    - sound-theme-freedesktop
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
