name       : mate-media
version    : 1.14.1
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-media-1.14.1.tar.xz : d7f55665bf919eb0cbc7583aa99d0c8a76ced4ef5ecb3cb29389dbc47c02c587
license    :
    - GPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    MATE Volume Control Applet
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(unique-3.0)
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
