name       : mate-media
version    : 1.24.0
release    : 18
source     :
    - https://github.com/mate-desktop/mate-media/archive/v1.24.0.tar.gz : 3df0c92a592e28d2c6d2fdb1db0ed4c657330754d5253142ec0172efa77fc211
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    This package contains a few media utilities for the MATE desktop, including a volume control.
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(mate-desktop-2.0)
    - mate-common
rundeps    :
    - sound-theme-freedesktop
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
