name       : mate-media
version    : 1.20.0
release    : 10
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-media-1.20.0.tar.xz : 99c50f56c93c5a010806658525b189c2fe7f38802c2f5d6ab79286c4ece16b27
license    :
    - GPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    MATE Volume Control Applet
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(mate-desktop-2.0)
rundeps    :
    - sound-theme-freedesktop
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
