name       : mate-media
version    : 1.20.1
release    : 12
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-media-1.20.1.tar.xz : 49273998491d802df97306c10dfd49178fc266ddbce3f0b2ef61390c503d64b5
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : MATE Volume Control Applet
description: |
    MATE Volume Control Applet
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatemixer)
    - pkgconfig(mate-desktop-2.0)
rundeps    :
    - sound-theme-freedesktop
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
